.TH "passim" "1" "" 0.1.0 "A local caching server"
.hy
.SH
NAME
.PP
\f[B]passim\f[R] — client control of the local caching server
.SH
SYNOPSIS
.PP
\f[B]passim\f[R] [CMD]
.SH
DESCRIPTION
.PP
This tool allows an administrator to display and share files using passim.
.SH
OPTIONS
.PP
The passim command takes various options depending on the action.
Run \f[B]passim --help\f[R] for the full list.
.SH
EXIT STATUS
.PP
Commands that successfully execute will return “0”, with generic failure as “1”.
.SH
BUGS
.PP
See GitHub Issues: <https://github.com/hughsie/passim>
.SH
