.TH passim 1 "0.1.0" "A local caching server"
.SH NAME
passim \- client control of the local caching server
.SH SYNOPSIS
.B passim
[CMD]
.SH DESCRIPTION
This tool allows an administrator to display and share files using passim.
.SH OPTIONS
The passim command takes various options depending on the action.
Run 
.B passim --help
for the full list.
.SH EXIT STATUS
Commands that successfully execute will return "0", with generic failure as "1".
.SH BUGS
See GitHub Issues: <https://github.com/hughsie/passim>
Changes made:
