FROM debian:unstable

RUN apt-get update -qq
RUN apt-get install -yq --no-install-recommends \
	gnutls-dev \
	gobject-introspection \
	libgirepository1.0-dev \
	libglib2.0-bin \
	libglib2.0-dev \
	libsoup-3.0-dev \
	libsystemd-dev \
	meson \
	ninja-build \
	pkg-config \
	shared-mime-info

# Meson is too old in unstable, and that won't change until Buster is released
# RUN pip3 install meson --break-system-packages

WORKDIR /build
